### ISSUE TITLE
error on Window 8, node 0.10.7

### ISSUE THREAD

**Issue by alexander-akait** [spacenick/jedi-crawler#1]
``` javascript
jedi.crawl('http://en.wikipedia.org/wiki/', function(err, data){
    console.log(err);
    console.log(data);
});
```

generate error 
events.js:72
throw er; // Unhandled 'error' event
^
Error: spawn ENOENT
at errnoException (child_process.js:980:11)
at Process.ChildProcess.handle.onexit (childprocess.js:771:34)

Because the path to phantomjs is wrong(strange behavior), adding option 'phantomPath'

``` javascript
phantom.create(callback, {
        parameters:{'load-images':'no','ignore-ssl-errors':'yes'}, phantomPath:'C:\\Path\\To\\phantomjs.exe'
    });
```

Solves this problem. Maybe add option for config phantomjs(some properties)?

**Comment by spacenick** [comment]
Thanks man gonna look into it. This is really messy right now gonna clean that up for shu

—
Nicolas Kermarc
